//! # Partition Table
//!
//! Parses ESP-IDF partition table CSV files and emits Rust constants
//! for a named partition's offset and size.
//!
//! The CSV format is defined by the
//! [ESP-IDF documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/partition-tables.html):
//!
//! ```text
//! # Name, Type, SubType, Offset, Size, Flags
//! nvs,    data, nvs,     0x9000, 0x6000,
//! factory,app,  factory, 0x10000, 1M,
//! ```
//!
//! - Lines starting with `#` are comments.
//! - Whitespace around fields is ignored.
//! - The `Offset` and `Size` fields accept decimal, hex (`0x…`), or
//!   suffixed values (`K` = 1024, `M` = 1024 × 1024).
//! - Either field may be blank or `N/A` when offsets are resolved at
//!   build time by `gen_esp32part.py`.
//! - The `Flags` column is optional.

use csv::{ReaderBuilder, Trim};
use std::fmt::Write as _;
use std::num::ParseIntError;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Errors that can occur when reading a partition table CSV.
#[derive(Debug, Error)]
pub enum PartitionError {
    /// The CSV file could not be read or parsed.
    #[error("CSV error: {0}")]
    Csv(#[from] csv::Error),

    /// A numeric field could not be parsed.
    #[error("failed to parse value: {0}")]
    ParseInt(#[from] ParseIntError),

    /// No partition with the requested name was found.
    #[error("partition '{0}' not found")]
    NotFound(String),

    /// The partition's offset or size is blank / `N/A` and has not been
    /// resolved by `gen_esp32part.py`.
    #[error(
        "partition '{name}' has a blank or N/A {field} \
         (must be resolved by gen_esp32part.py first)"
    )]
    BlankField { name: String, field: &'static str },

    /// Failed to write generated Rust constants.
    #[error("failed to write generated config to {path}")]
    EmitRust {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// A single resolved partition entry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Partition {
    pub name: String,
    pub part_type: String,
    pub subtype: String,
    pub offset: u32,
    pub size: u32,
}

impl Partition {
    /// Write Rust constants for this partition to a file in `out_dir`.
    ///
    /// Generates `partition_config.rs` containing:
    ///
    /// ```text
    /// // Auto-generated by littlefs2-pack — do not edit.
    /// pub const PARTITION_NAME: &str = "littlefs";
    /// pub const PARTITION_OFFSET: u32 = 0x200000;
    /// pub const PARTITION_SIZE: u32 = 0xE00000;
    /// ```
    pub fn emit_rust(&self, out_dir: &Path) -> Result<(), PartitionError> {
        let path = out_dir.join("partition_config.rs");

        let mut content = String::new();
        writeln!(
            content,
            "// Auto-generated by littlefs2-pack — do not edit."
        )
        .unwrap();
        writeln!(content).unwrap();
        writeln!(
            content,
            "pub const PARTITION_NAME: &str = \"{}\";",
            self.name
        )
        .unwrap();
        writeln!(
            content,
            "pub const PARTITION_OFFSET: u32 = {:#X};",
            self.offset
        )
        .unwrap();
        writeln!(content, "pub const PARTITION_SIZE: u32 = {:#X};", self.size).unwrap();

        std::fs::write(&path, content).map_err(|source| PartitionError::EmitRust { path, source })
    }
}

/// Read an ESP-IDF partition table CSV and return the [`Partition`]
/// whose name matches `target_name`.
///
/// See the [module-level docs](self) for details on the expected CSV format.
pub fn get_partition(
    csv_path: impl AsRef<Path>,
    target_name: &str,
) -> Result<Partition, PartitionError> {
    let mut rdr = ReaderBuilder::new()
        .comment(Some(b'#'))
        .has_headers(false)
        .trim(Trim::All)
        .flexible(true)
        .from_path(csv_path)?;

    // Fields: Name (0), Type (1), SubType (2), Offset (3), Size (4), Flags (5)
    for result in rdr.records() {
        let record = result?;

        let name = match record.get(0) {
            Some(n) if n == target_name => n,
            _ => continue,
        };

        let part_type = record.get(1).unwrap_or_default().to_string();
        let subtype = record.get(2).unwrap_or_default().to_string();

        let offset_str = record
            .get(3)
            .ok_or_else(|| PartitionError::NotFound(target_name.to_string()))?;
        let size_str = record
            .get(4)
            .ok_or_else(|| PartitionError::NotFound(target_name.to_string()))?;

        let offset = parse_field(offset_str, target_name, "offset")?;
        let size = parse_field(size_str, target_name, "size")?;

        return Ok(Partition {
            name: name.to_string(),
            part_type,
            subtype,
            offset,
            size,
        });
    }

    Err(PartitionError::NotFound(target_name.to_string()))
}

/// Parse an offset or size field, returning [`PartitionError::BlankField`]
/// for empty / `N/A` values.
fn parse_field(value: &str, name: &str, field: &'static str) -> Result<u32, PartitionError> {
    if value.is_empty() || value.eq_ignore_ascii_case("n/a") {
        return Err(PartitionError::BlankField {
            name: name.to_string(),
            field,
        });
    }
    parse_size_value(value).map_err(Into::into)
}

/// Parse a value that may be hex (`0x…`), decimal, or use `K`/`M` suffixes.
fn parse_size_value(s: &str) -> Result<u32, ParseIntError> {
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u32::from_str_radix(hex, 16)
    } else if let Some(num) = s.strip_suffix('K').or_else(|| s.strip_suffix('k')) {
        num.parse::<u32>().map(|n| n * 1024)
    } else if let Some(num) = s.strip_suffix('M').or_else(|| s.strip_suffix('m')) {
        num.parse::<u32>().map(|n| n * 1024 * 1024)
    } else {
        s.parse::<u32>()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_test_csv(dir: &tempfile::TempDir) -> PathBuf {
        let path = dir.path().join("partitions.csv");
        let mut f = std::fs::File::create(&path).unwrap();
        write!(
            f,
            "\
# ESP32-S3 partition table
# Name,      Type, SubType,  Offset,     Size
nvs,         data, nvs,      0x9000,     0x6000
phy_init,    data, phy,      0xf000,     0x1000
factory,     app,  factory,  0x10000,    0x1F0000
littlefs,    data, fat,      0x200000,   0xE00000
"
        )
        .unwrap();
        path
    }

    fn write_ota_csv(dir: &tempfile::TempDir) -> PathBuf {
        let path = dir.path().join("partitions.csv");
        let mut f = std::fs::File::create(&path).unwrap();
        write!(
            f,
            "\
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs,      data, nvs,      0x9000,  0x4000
otadata,  data, ota,      0xd000,  0x2000
phy_init, data, phy,      0xf000,  0x1000
factory,  app,  factory,  0x10000,  1M
ota_0,    app,  ota_0,    ,         1M
ota_1,    app,  ota_1,    ,         1M
"
        )
        .unwrap();
        path
    }

    #[test]
    fn finds_partition_with_all_fields() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_test_csv(&dir);

        let p = get_partition(&path, "littlefs").unwrap();
        assert_eq!(p.name, "littlefs");
        assert_eq!(p.part_type, "data");
        assert_eq!(p.subtype, "fat");
        assert_eq!(p.offset, 0x200000);
        assert_eq!(p.size, 0xE00000);
    }

    #[test]
    fn finds_factory_with_hex_offset() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_test_csv(&dir);

        let p = get_partition(&path, "factory").unwrap();
        assert_eq!(p.offset, 0x10000);
        assert_eq!(p.size, 0x1F0000);
    }

    #[test]
    fn size_multiplier_suffix() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_ota_csv(&dir);

        let p = get_partition(&path, "factory").unwrap();
        assert_eq!(p.size, 1024 * 1024);
    }

    #[test]
    fn blank_offset_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_ota_csv(&dir);

        let err = get_partition(&path, "ota_0").unwrap_err();
        assert!(matches!(
            err,
            PartitionError::BlankField {
                field: "offset",
                ..
            }
        ));
    }

    #[test]
    fn not_found() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_test_csv(&dir);

        assert!(matches!(
            get_partition(&path, "nonexistent"),
            Err(PartitionError::NotFound(_))
        ));
    }

    #[test]
    fn emit_rust_generates_constants() {
        let p = Partition {
            name: "littlefs".to_string(),
            part_type: "data".to_string(),
            subtype: "fat".to_string(),
            offset: 0x200000,
            size: 0xE00000,
        };

        let dir = tempfile::tempdir().unwrap();
        p.emit_rust(dir.path()).unwrap();

        let contents = std::fs::read_to_string(dir.path().join("partition_config.rs")).unwrap();

        assert!(contents.contains("pub const PARTITION_NAME: &str = \"littlefs\";"));
        assert!(contents.contains("pub const PARTITION_OFFSET: u32 = 0x200000;"));
        assert!(contents.contains("pub const PARTITION_SIZE: u32 = 0xE00000;"));
    }

    #[test]
    fn parse_size_value_variants() {
        assert_eq!(parse_size_value("0x10000").unwrap(), 0x10000);
        assert_eq!(parse_size_value("65536").unwrap(), 65536);
        assert_eq!(parse_size_value("64K").unwrap(), 64 * 1024);
        assert_eq!(parse_size_value("1M").unwrap(), 1024 * 1024);
    }
}
