[target.xtensa-esp32s3-none-elf]
runner = "littlefs flash --config ./littlefs.toml"

[env]
DEFMT_LOG = "info"
ESP_HAL_CONFIG_PSRAM_MODE = "quad"
CFLAGS_xtensa-esp32s3-none-elf = "-mlongcalls"


[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
