[target.xtensa-esp32s3-none-elf]
# runner = "espflash flash --monitor --chip esp32s3 --log-format defmt"
runner = "espflash flash --partition-table partitions.csv --flash-size 16mb"

[env]
DEFMT_LOG = "info"
ESP_HAL_CONFIG_PSRAM_MODE = "quad"
CFLAGS_xtensa-esp32s3-none-elf = "-mlongcalls"


[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
