[image]
block_size = 4096
page_size = 256
read_size = 16
write_size = 512
block_count = 3096
# of -1 will be applied.
block_cycles = -1


[directory]
root = "./test-website"
depth = -1
ignore_hidden = true
gitignore = true
repo_gitignore = true
glob_ignores = []
glob_includes = []

[flash.firmware]
command = "espflash flash --monitor --partition-table partitions.csv --log-format defmt {path}"

[flash.filesystem]
command = "espflash write-bin {address} {path}"
# The ESP partitition table and name to read the address from
partition_table = "./partitions.csv"
partition_name = "littlefs"
